---
bibliography: "quantificational-logic.bib"
number-sections: true
crossref:
  chapters: true
---

{{< include /assets/macros/macros.qmd >}}

# Quantificational Logic

{{< include introduction.qmd >}}

{{< include syntax.qmd >}}

:::{.content-hidden when-profile="lecture-10"}

{{< include semantics.qmd >}}

:::

:::{.content-hidden when-profile="lecture-10"}
:::{.content-hidden when-profile="lecture-11"}

{{< include identity.qmd >}}

:::
:::

:::{.content-hidden when-profile="lecture-10"}
:::{.content-hidden when-profile="lecture-11"}
:::{.content-hidden when-profile="lecture-12"}

## Proofs in Quantificational Logic

### Universal Introduction and Existential Elimination

Now that we have introduced a formal language for quantificational logic and
given it a semantics, the next step is to say how we reason and give proofs in
the language.

We will represent proofs in quantificational logic using the same Fitch-style
notation for nested sequences that we employed in the context of syllogistic and
propositional logic. Many of the rules of our proof system will be rules that we
have already seen and used. In fact, our system will inherit all of the rules
that we introduced for reasoning in propositional logic. Thus, recall, were the
elimination and introduction rules for the propositional connectives:

Negation:

($\neg$E): From the sentence $\neg\neg\ph$, you may infer the sentence $\ph$.

($\neg$I): If from the hypothesis $\ph$ you can derive $\psi$ and $\neg\psi$,
you may infer the sentence $\neg\ph$.

Conditional:

($\imp$E): From $\ph$ and $\ph\imp\psi$, you may infer $\psi$.

($\imp$I): If from the hypothesis $\ph$ you can derive $\psi$,
you may infer the sentence $\ph\imp\psi$.

Conjunction:

($\conj$E): From $\ph\conj\psi$, you may infer either the sentence $\ph$ or the sentence $\psi$.

($\conj$I): From $\ph$ and $\psi$, you may infer the sentence $\ph\conj\psi$.

Disjunction:

($\vee$E): If from the hypothesis $\ph$ you can derive $\chi$ and from the
hypothesis $\psi$ you can derive $\chi$, then from $\ph\vee\psi$ you may infer
the sentence $\chi$.

($\vee$I): From either $\ph$ or $\psi$, you may infer the sentence
$\ph\vee\psi$.

Biconditional:

($\iff$E): From $\ph$ and $\ph\iff\psi$, you may infer $\psi$, and from $\psi$
and $\ph\iff\psi$, you may infer $\ph$.

($\iff$I): If from the hypothesis $\ph$ you can derive $\psi$ and from the
hypothesis $\psi$ you can derive $\ph$, then you may infer $\ph\iff\psi$.

In addition these rules we will also add introduction and elimination rules for
the universal and existential quantifiers. The simplest of these rules are the
rules of universal elimination ($\forall$E) and existential introduction
($\exists$I). The rule of universal elimination says that from a sentence of the
form $\forall x(\ph)$, we may infer any instantiation of the formula that is quantified
over, namely, $\ph(x)$. Thus, the rule can be stated as follows:

($\forall$E): Let $x$ be any variable and let $\ph(x)$ any open formula in which $x$
occurs freely. From $\forall x(\ph)$, you may infer $\ph(a)$, for any constant
$a$.

Consider the argument:

$$ Pa, \forall x(Px\rightarrow Qx)\proves Qa $$

Here is a proof:

:::{.lproof}

      1. |  Pa     [Premise]
      2. |  \forall x(Px\rightarrow Qx)   [Premise]
      3. |  Pa\rightarrow Qa              [$\forall$E: 2]
      4. |  Qa                            [$\rightarrow$E: 1, 3]

:::

We apply the rule of universal elimination to get from line 2 in the proof to
line 3. In doing so, we instantiate the open formula $Px\imp Qx$ by replacing
every free occurrence of $x$ in the formula with the constant $a$.

Here is a proof of the first argument introduced at the beginning of this chapter:

$$
\forall x(Cx\rightarrow (Fx \vee Sx)),Ca\wedge
\neg Fa\proves Sa
$$

:::{.lproof}

      1. | \forall x(Cx\rightarrow (Fx \vee Sx))     [Premise]
      2. | Ca\rightarrow (Fa\vee Sa)                 [$\forall$E: 1]
      3. | Ca\wedge \neg Fa                           [Premise]
      4. | Ca                                         [$\wedge$E: 3]
      5. | \neg Fa                                    [$\wedge$E: 3]
      6. | Fa \vee Sa                                 [$\rightarrow$E: 3, 4]
      7. |  |_ Sa                                     [Hypothesis]
      8. |  |_ Fa                                     [Hypothesis]
      9. |  |  |_ \neg Sa                             [Hypothesis]
      10. | |  |  Fa                                  [Reiteration: 8]
      11. | |  |  \neg Fa                             [Reiteration: 5]
      12. | |  \neg\neg Sa                            [$\neg$I: 10, 11]
      13. | |  Sa                                     [$\neg$E: 12]
      14. | Sa                                        [$\vee$E: 6, 7, 13]

:::

Now for the rule of existential introduction ($\exists$ I). This rule works like
the reverse of universal elimination. We infer from an instantiation $\ph(a)$ of an open
formula $\ph(x)$, the existentially quantified sentence $\exists x\ph(x)$.

($\exists$I): Let $x$ be any variable and let $\ph(x)$ be any open formula in
which $x$ occurs freely. For any constant $a$, from $\ph(a)$, you may infer $\exists x(\ph)$.

The proof of the following argument illustrates how this rule can be applied:

$$
Pa\proves \exists y(Py\vee Qy)
$$

:::{.lproof}

      1. | Pa        [Premise]
      2. | Pa \vee Qa [$\vee$I: 1]
      3. | \exists y(Py\vee Qy) [$\exists$I: 2]

:::

In the step from line 2 to 3, we use the rule ($\exists$I) to infer from the
formula $\ph(a)$, where $\ph(y)$ is the open formula $Py \vee Qy$, the
existential sentence $\exists y(Py\vee Qy)$. Now here is a proof of the second
argument introduced at the beginning of the chapter:

$$
\forall x(\exists y(Pyx\wedge Ayx)\rightarrow Tx), Paj\proves Aaj\rightarrow Tj
$$

:::{.lproof}

      1. | \forall x(\exists y(Pyx\wedge Ayx)\rightarrow Tx)      [Premise]
      2. |  \exists y(Pyj\wedge Ayj)\rightarrow Tj                [$\forall$E: 1]
      3. |  |_ Aaj                                                [Hypothesis]
      4. |  |  Paj                                                [Premise]
      5. |  |  Paj \wedge Aaj                                     [$\wedge$I: 3, 4]
      6. |  |  \exists y(Pyj \wedge Ayj)                          [$\exists$I: 5]
      7. |  |  \exists y(Pyj\wedge Ayj)\rightarrow Tj             [Reiteration: 2]
      8. |  |  Tj                                                 [$\rightarrow$E: 6, 7]
      9. |  Aaj\rightarrow Tj                                     [$\rightarrow$I: 8]

:::

Exercise: Proofs

### Universal Introduction and Existential Elimination

Let's now turn to the rule of universal introduction ($\forall$I). At first
blush, it might seem difficult to imagine how we can prove a universal
statement. After all, universal statements say something about _everything_ in
the domain, so to establish a universal claim such as $\forall x(\ph)$ one
instance at a time would require us to first prove all of the infinitely many claims:

$$ \ph(a), \ph(b), \ph(c), \ldots $$

Who has time for that? The rule universal introduction is based on the idea that
we can shortcut this interminable procedure, by instead proving that the claim
$\ph$ holds for just one individual object, but one object which, for all we
know, may be anything.

Here is the idea, suppose that we have proven that $\ph(a)$, for some constant
$a$. And now suppose that looking back at the proof, what we find is that the
constant $a$ is nowhere mentioned in any of the premises appealed to in the
proof. Nor does $a$ occur in any of the undischarged hypotheses that are in
effect at the point at which $\ph(a)$ is established. Then, since none of our
substantive assumptions---our premises or hypothesis---put any constraints on
what the object the constant $a$ refers to, and yet nonetheless we have still been
able to prove that $\ph(x)$ holds of $a$, then it must be the case that $\ph(x)$ would hold
for _any_ x, whatsoever; that is, it must be the case that $\forall x(\ph)$.
Here is the rule that codifies this sort of reasoning:

($\forall$I): Let $x$ be any variable and let $\ph(x)$ be any open formula in which $x$
occurs freely. From $\ph(a)$, where $a$ is any constant that does not occur in any
premise or undischarged hypothesis, one may infer $\forall x(\ph)$.

Here is an example of how the rule can be applied:

$$
\forall x(Px\rightarrow Qx), \forall x Px\proves \forall x Qx
$$

:::{.lproof}

      1. |  \forall x(Px\rightarrow Qx)      [Premise]
      2. |  Pa\rightarrow Qa                 [$\forall$E: 1]
      3. |  \forall x(Px)                    [Premise]
      4. |  Pa                               [$\forall$E: 3]
      5. |  Qa                               [$\rightarrow$E: 2, 4]
      6. | \forall x(Qx)                     [$\forall$I: 5]

:::

The rule of universal introduction is appealed to in the final step of the proof
in order to infer $\forall x(Qx)$ from $Qa$. Why is this inference justified?
How can we infer that everything has the property $Q$ from the fact that just
one thing, $a$, has it? The answer is that the object named by the constant $a$,
as it appears in line 5, serves the role of an arbitrary object. If you look at
the premises appealed to in the argument, they say nothing at all about $a$. So, as far
as the premises are concerned, $a$ could stand for anything. If, despite this
indeterminacy of reference, we can still establish that $Qa$, it can only be
because everything has the property $Q$.

It may be instructive, at this point, to consider an incorrect application of the rule.

$$
\forall x(Px\rightarrow Qx), Pa\proves \forall x Qx
$$

:::{.lproof}

      1. |  \forall x(Px\rightarrow Qx)      [Premise]
      2. |  Pa\rightarrow Qa                 [$\forall$E: 1]
      4. |  Pa                               [Premise]
      5. |  Qa                               [$\rightarrow$E: 2, 4]
      6. | \forall x(Qx)                     [$\forall$I: 5 \qquad\color{red}\textrm{No!}]

:::

Here, we are not allowed to generalize from $Qa$ to $\forall x(Qx)$. This is
because, as referred to in line 5, $a$ is not just any object. It is a
particular object that the second premise tells us possesses the property $P$. It
is this fact about $a$ that allows us to infer that $Qa$ and so it would be
wrong to take this result and generalize to all objects in the domain.

The following argument gives another example of how the rule of universal introduction can be
applied:

$$ \neg \exists Px\proves\forall x\neg Px $$

:::{.lproof}

      1. |  |_ Pa       [Hypothesis]
      2. |  |  \exists x Px   [$\exists$I: 1]
      3. |  |  \neg\exists x Px  [Premise]
      4. |  \neg Pa              [$\neg$I: 2, 3]
      5. |  \forall x \neg Px    [$\forall$I: 4]

:::

Note here that while the constant $a$ appears in the hypothesis in line 1, at
the point at which the rule $\forall I$ is applied to it in line 4, that
assumption has been discharged. And so this is a correct application of the rule.

Now, let's turn to the last of our rules, existential elimination. This rule is
suppose to allow us to infer

:::
:::
:::

## References {.unnumbered}

$$
$$
