## The Syntax of Quantificational Logic

Before introducing the formal language of quantificational logic, let's begin by
considering a few specific arguments. By formalizing these arguments, we will
get a rough sense for the various kinds of syntactic items that we will need to
include in our language. Consider the argument:

$$
\frac{\textrm{Everyone in the classroom is either in first or second
grade\hspace{3mm},\hspace{3mm} Amy is in the classroom and she is not
in first grade}}{\textrm{Amy is in second grade}}
$$

Take the second premise:

$$
\textrm{Amy is in the classroom and she is not
in first grade}
$$

This looks like a propositional compound, more specifically, it looks like a
conjunction, and even more specifically a conjunction with a negated right
conjunct. Thus, in the language of propositional logic, we might have formalized
this sentence as follows:

$$C\wedge\neg F$$

where

$C$: Amy is in the classroom

$F$: Amy is in first grade

So a first observation is that to express propositional compounds, our formal language will need to
include all the propositional connectives that we introduced in the context of
propositional logic, namely:

$$ \neg, \conj, \disj, \rightarrow, \leftrightarrow $$

The above formalization in the language of propositional logic is probably not
going to suffice. To see why, consider the conclusion of the argument:

$$\textrm{Amy is in second grade}$$

How should we formalize this sentence? Since it is not a propositional compound,
in the language of propositional logic it would simply be formalized by another
atomic sentence, such as $S$. But representing the second premise as
$C\wedge\neg F$ and the conclusion as $S$ obscures the crucial relationship that
obtains between the two, namely, that they are both sentences which say
something about one and the same person, Amy. So both sentences must somehow
refer to Amy. Now, if we want to refer to Amy in our formal language, we will
need to give her a name. So, our formal language will also need to have names of
individuals. For now, let's use the letter '$a$' as a name for Amy.

The second premise says two things about Amy. The first is that she is in the
classroom and the second is that she is not in the first grade. When we say that
Amy is in the classroom, we are ascribing to Amy a specific property. So, our
language will need to include not only names for objects, but names for
properties as well. Let $C$ be a name for the property '... is in the
classroom'. We want to assert that this property holds of Amy. To attribute this
property to Amy, we will first write down a name of the property, followed by a
name of Amy. In this way, the claim that Amy is in the classroom will be
expressed:

$$ Ca $$

Let $F$ name the property '... is in the first grade'. Then, all told, the
second premise can be formalized as follows:

$$ Ca\wedge \neg Fa$$

While this rendering conveys the compound propositional structure just as
clearly as the formalization of the sentence in propositional logic, it adds
internal structure to the component sentences out of which this compound is
built. Instead of treating these component sentences as structureless atoms, we
have now indicated something about these sentences, namely, that they attribute
properties to a specific individual, an individual who is referred to by name
and who can be referred to again by that same name elsewhere in the argument.
For example, letting $S$ be the property '... is in second grade', the
conclusion of the argument can now be rendered: $$ Sa $$

Now, let's look at the first premise of the argument:

$$
\textrm{Everyone in the classroom is either in first or second
grade}
$$

In the language of syllogistic logic, we might have formalized this sentence as
follows:

$$\all{C}{E}$$

where the term $C$ denotes the property '... is in the classroom' and $E$ the
property '... is either in first or second grade'. This sort of rendering is
also unlikely to be adequate because it doesn't expose the disjunctive structure
of the predicate term, which plays an essential role in the reasoning.

Now, this sentence clearly says something about individuals, but it does so
without mentioning anyone by name. Since the sentence doesn't name anyone, let's
just imagine some arbitrary individual, and call this arbitrary individual $x$.
What does the sentence imply about $x$? It implies that if $x$ is in the
classroom, then $x$ is either in first or second grade. Using the same notation
introduced in our above formalization, we can express this fact about $x$ as
follows:

$$ Cx \rightarrow (Fx \vee Sx) $$

What the premise says is that the above claim is true not just of some
particular individual, but of _every_ individual. To convey this fact, we need a
way of indicating that the claim is meant to be true _regardless_ of who $x$
stands for. We could indicate this as follows:

$$ \textrm{For all $x$: } Cx \rightarrow (Fx \vee Sx) $$

In the language of quantificational logic, in place of the prefix 'For all $x$:
...:' we write $\forall x(\cdots)$. The upside-down 'A' written before the name $x$ is
called a quantifier. More specifically, it is called the universal quantifier.
All told then, the first premise can be written:

$$\forall x(Cx\rightarrow (Fx \vee Sx))$$

To express this sentence, we needed to introduce two new elements into the
language: the universal quantifier and the symbol $x$. We will call the symbol
$x$ a _variable_. Syntactically, it will function very much like a name, but, as
we shall see, semantically variables will have a different meaning.

The entire argument, formalized in the language of quantificational logic is:

$$
\forall x(Cx\rightarrow (Fx \vee Sx)),Ca\wedge
\neg Fa\proves Sa
$$

We will later see how to assess the validity of this argument.

Now, let's examine the second argument mentioned above:

$$
\frac{\textrm{Anyone can go on the trip with a parent's
approval\hspace{3mm},\hspace{3mm} Adam is Julia's parent}}{\textrm{If Adam gives
Julia approval, she can go on the trip}}
$$

Consider the second premise:

$$ \textrm{Adam is Julia's parent} $$

This sentence says something not just about one individual, but about two,
namely Adam and Julia. What does it say about them? It says that they stand in a
certain relation to each other, in particular, that Adam is Julia's parent.
To capture this fact we will need to give a name to the two-place relation '... is a
parent of ---'. Let's call this relation $P$. To express the fact that Adam stands in this
relation to Julia, we will first write down the name of the relation, then the
names of Adam and Julia in that order. If '$a$' names Adam and '$j$' names Julia,
then we can formalize the sentence as follows:

$$ Paj $$

Note here that the order in which the names appears matters. If we had instead
written $Pja$ this would mean that Julia is a parent of Adam. This, of course,
is not the case since the relation of parent to child is asymmetrical. Why not
write $aRj$ to make the order a bit more perspicuous? We could, but our logic
will later allow for relations between three or more things, and the prefix (as
opposed to the infix) notation can be more straightforwardly adapted to handle
such complex relations.

So now we see that, in addition to names for properties, we will also need to
include in our language names for relations. Syntactically, names for relations
will function very much like names for properties, only instead of applying to a
single individual they will apply to two (or three, or possibly more)
individuals. We will call both names for properties and names for relations,
_predicates_. Predicates may be _unary_ if they denote properties of
individuals, or they may be _binary_ if they denote two-place relations, or they
may be _ternary_ if they denote three-place relations, or _quaternary_, etc..

Now let's look at the conclusion. Clearly, this is a conditional sentence. The
antecedent of the conditional is 'Adam gives Julia approval'. Again, this states
that a certain relation obtains between Adam and Julia, namely, the relation
'... gives approval to ---'. Let's use the binary predicate $A$ to stand for
this two-place relation. The consequent of the conditional is the sentence
'Julia can go on the trip'. Here we are simply ascribing a property to Julia.
Let $T$ be the unary predicate that names the property '... can go on the trip'.
Then the conclusion of the argument can be written: $$ Aaj\rightarrow Tj$$

Now for the first premise. This says something about individuals without naming
any individual explicitly. If $x$ and $y$ are two arbitrary individuals, then
the sentence implies that $x$ can go on the trip, provided $x$ gets the approval
of $y$ and $y$ is a parent of $x$. Let's focus on the proviso first, which
states that $x$ must have a parent's approval. We could write down this proviso
as follows: $$Pyx \wedge Ayx$$ Note that the proviso does not state that
$x$ needs the approval of _all_ of his or her parents, just that $x$ needs the
approval of some one of them. The first stronger proviso, requiring approval
from all parents, could be written: $$\forall y(Pyx \wedge Ayx)$$ But what we need
instead is a way to say something weaker like $$\textrm{For some $y$:} Pyx \wedge Ayx$$
To say this, we will introduce a second quantifier, which we will call the
_existential_ quantifier and which we will denote by the symbol, $\exists$. The
proviso can thus be written:

$$\exists y(Pyx\wedge Ayx)$$

This says that $x$ gets approval from some parent. What we want to say about $x$
is that if $x$ gets a parent's approval, then $x$ can go on the trip:

$$\exists y(Pyx\wedge Ayx)\rightarrow T(x)$$

What the first premise says is that this is true not just of some $x$, but of every
$x$. So, all told the premise can be written:

$$
\forall x(\exists y(Pyx\wedge Ayx)\rightarrow Tx)
$$

The argument can thus be formalized:

$$
\forall x(\exists y(Pyx\wedge Ayx)\rightarrow Tx), Paj\proves Aaj\rightarrow Tj
$$

Now that we have a sense of the types of syntactic item needed to formalize
arguments in quantificational logic, we can give a more precise specification of
the language, which we shall call L$_Q$. As usual, we begin by supplying
an alphabet for the language.

The alphabet for L$_Q$ includes an arbitrarily large stock of symbols
that we will refer to as _constants_. The constant symbols will serve as our
names for individual objects. In addition to constants, the language also
includes an arbitrarily large stock of symbols that we will refer to as
_variables_. Collectively, the constants and variables will be referred to as
_terms_. We could, of course, use whatever symbols we like for the terms of the
language, but we will generally adopt the convention of using lowercase letters
from the beginning or middle of the Latin alphabet for constants, and lowercase
letters from the end of the Latin alphabet for variables.

- Terms:
  - Constants: $a,b,c,...j,k,l,...$

  - Variables: $x,y,z,u,v,w,...$

In addition to the terms, we will also need predicate symbols that can serve as
names for properties and relations. Again, any symbols will do, but, by
convention, we will typically use uppercase Latin letters for predicate symbols.

- Predicates: $A,B,C,\ldots,P,Q,R,\ldots$

We will assume that every predicate in the language has associated with it a
predetermined number, called its _arity_, which indicates how many objects are
related by the property or relation it signifies. If the arity of a predicate is
$2$, say, then it is a binary predicate and names a two-place relation. If it is
$1$, then it is a unary predicate and names a property. When we wish to indicate
that the predicate symbol $P$ has arity $n$, we will denote it by $P^n$.

The language of quantificational logic also include the five propositional
connectives:

- Propositional Connectives: $\neg, \wedge, \vee, \imp, \iff$

and parentheses that can be used for delimiting their scope:

- Parentheses: $(\,,\,)$

Finally, the language also include two additional symbols, the
universal and existential quantifiers:

- Quantifiers: $\forall, \exists$

That's it. If you go back to the arguments that we just formalized, you can
verify for yourself that every symbol appearing in every sentence in these
arguments falls into one of these five categories.

Next, we need to say which expressions---that is, which strings of symbols from the
alphabet---constitute sentences of L$_Q$. First we will
define the notion of a _formula_ of L$_Q$.

:::{#def-formula .definition}
The _formulas_ of L$_Q$ are defined inductively as follows:

1. If $P^n$ is a predicate and $a_1,\ldots,a_n$ are terms, then:
   $$P a_1a_2\cdots a_n$$
   is a formula.

2. If $\ph$ is a formula, then $\neg\ph$ is a formula.

3. If $\ph$ and $\psi$ are formulas and $\ast$ is a binary propositional
   connective, then $\ph\ast\psi$ is a formula.

4. If $\ph$ is a formula and $v$ is a variable, then $\forall v(\ph)$ is a
   formula.

5. If $\ph$ is a formula and $v$ is a variable, then $\exists v(\ph)$ is a
   formula.

:::

Assuming that $P$ is a unary predicate, $R$ a binary predicate, and $S$ a
ternary predicate, the following expressions are all formulas of L$_Q$:

:::{#sentences-Lp}

$$ Pa $$

$$ Sxba$$

$$ Rax\leftrightarrow \neg Rbx$$

$$\forall x(Rxa\rightarrow Px)$$

$$\neg\exists y (Pz \wedge \forall z(Rxy\vee Pz))$$

$$\exists x(\forall y((Pa \wedge Px)\rightarrow Rxy))$$

:::

Notice that, in some of these formulas, there are variables that do not occur in
the scope of a corresponding quantifier. Take, for example, the formula $Rax\leftrightarrow \neg
Rbx$. In this formula $x$ occurs, but it does not fall within the scope of
either $\forall x$ or $\exists x$. In this case, we say that $x$ occurs _freely_
in the formula. Contrast this with the next formula:

$$\forall x(Rxa\rightarrow Px)$$

Ignoring the $x$ attached to the quantifier, the other two occurrences of the
variable $x$ both occur within the (parenthetically delimited) scope of the
quantifier $\forall x$. In this case, we say that these occurrences of $x$ are
_bound_. Now, consider the formula:

$$\neg\exists y (Pz \wedge \forall z(Rxy\vee Pz))$$

Ignoring the variables attached to quantifiers, which variables in the formula
are free and which bound? The first occurrence of the variable $z$ is free, as is
the only occurence of the variable $x$, but the one occurrence of the variable
$y$ and the second occurrence of the variable $z$ are both bound.

We now define the sentences of the language as follows

:::{#def-formula .definition}
A _sentence of L$_Q$_ is a formula in which no variable occurs freely.
:::

Only sentences of the language can serve as the premises or conclusion of an
argument, but non-sentential formulas are important as well. These so-called
'open' formulas effectively allow us to introduce into the language new
properties and relations not named by the predicates of the language. Recall our
attempt to formalize the claim:

$$ \textrm{Anyone can go on the trip if they are given a parent's approval}$$

To capture the relevant proviso, we began by writing down the following formula:

$$ Pyx \wedge Ayx $$

This is an open formula, not a sentence, since the variables $x$ and $y$ do not
occur within the scope of any quantifiers. Because $x$ and $y$ occur freely in
this formula, the formula in effect says something about the particular items to
which they refer. What does it say about these items? It says that $x$ and $y$
stand in a certain relation to one another, namely, the relation of $y$ being a
parent of $x$ who gives to $x$ their approval. Notice that this relation is not
named by any of the primitive predicates that we used in our formalization of
the argument. Rather, it may be thought of as a newly defined binary relation
(we will discuss how to apply this relation shortly).

To capture the proviso, we then said that $x$ satisfies the required condition
if there is _some_ person who stands in this defined relation to $x$. To express
this fact, we applied the existential quantifier to the above formula, which
resulted in the formula:

$$ \exists y(Pyx \wedge Ayx) $$

Notice that the variable $y$ no longer occurs freely in the formula since it has
been captured, or bound, by the quantifier $\exists y$. Still this formula is
not a sentence, since both occurrences of the variable $x$ still occur freely in
it. Thus, the formula still says something about $x$. What does it say? It says
that $x$ has a certain property, namely the property of having some parent's
approval. This again can be thought of as a defined property, since the language
as specified does not include a unary predicate that names this property
directly. To see that this property no longer says anything about $y$, note that
we could define the same property by replacing every occurrence of $y$ with a
different variable, say $z$:

$$ \exists z(Pzx \wedge Azx) $$

What does this formula say about $x$? The same thing as it did before the
variable replacement, namely, that $x$ has a parent who has given them approval.
Thus, bound variables don't really name anything, they are, so to speak, 'dummy'
names. Like pronouns, they are useful, to ensure consistency of reference across
a discursive context, as when we say:

$$
\textrm{There is something on the table, and \emph{it} wasn't there before.}
$$

Now that we have defined the property of an individual having parental approval,
the first premise in the argument is easy to formalize. It says that anyone who
has that property can go on the trip.

$$
\forall x(\exists z(Pzx \wedge Azx)\rightarrow T(x))
$$

We have at last arrived at a sentence. All the variables are now bound, and so
they are all just dummy names. This means that we can now ask whether the
sentence is true or false without saying anything about what $x$ and $z$ stand
for.

:::{#exr-free-versus-bound .exercise}

{{< include /content/exercises/free-versus-bound.qmd >}}

:::

:::{#exr-translations-to-Lq .exercise}

{{< include /content/exercises/translations-to-Lq.qmd >}}

:::
