project:
  output-dir: _course/lecture-7
  type: book

book:
  chapters:
      - index.qmd
      - content/front-matter/00-introduction/introduction.qmd
      - content/body/chapters/01-argument-validity-proof/argument-validity-proof.qmd
      - content/body/chapters/02-propositional-logic/propositional-logic.qmd
  appendices: 
      - content/back-matter/solutions.qmd 
