### Truth-Functional Completeness

When we set up the formal language L$_P$, we posited five propositional connectives, $\neg$,
$\conj$, $\disj$, $\imp$, and $\iff$. But why did we stop there? Is there
something special about this particular set of connectives? Why did we not add more
connectives to make our language even more expressive?

When we talk about the expressive power of the language, what we mean to ask is
whether or not our language is capable of capturing various truth-functional
relationships that may obtain between the atoms. Truth-functional relationships
are, after all, the only kind of relationship that we are interested in. Here is
one way of thinking about this question: consider a truth table in which we fill
in the final column in a totally haphazard way, randomly assigning $\true$'s and
$\false$'s to the rows. The resulting truth table will express some, possibly
complex, truth-functional relationship between the atoms appearing in the
initial columns. The question is, are we able to express that relationship by
means of a sentence of the language L$_P$. Or are there some truth-functional
relationships for which we would need to add to the language additional propositional connectives?

As we shall see, the answer to this last question is no. Our current set of
connectives is truth-functionally complete, in the sense that it is able to
express any truth-functional relationship whatsoever. Moreover, it is even
redundant in the sense that we could omit certain connectives from the language
without any loss of expressive power.

Consider the following truth table in which the last column has been randomly
populated:

|   $P$    |   $Q$    |   $R$    |   ???    |
| :------: | :------: | :------: | :------: |
| $\true$  | $\true$  | $\true$  | $\true$  |
| $\true$  | $\true$  | $\false$ | $\false$ |
| $\true$  | $\false$ | $\true$  | $\true$  |
| $\true$  | $\false$ | $\false$ | $\false$ |
| $\false$ | $\true$  | $\true$  | $\true$  |
| $\false$ | $\true$  | $\false$ | $\true$  |
| $\false$ | $\false$ | $\true$  | $\false$ |
| $\false$ | $\false$ | $\false$ | $\false$ |

Is there a sentence of L$_P$ that corresponds to this truth table? Note that
such a sentence should be $\true$ iff its arguments are those given in either
the first, third, fifth, or sixth rows of the table. So, we might start by
formulating our desired sentence as a disjunction of these four possibilities:

$$
  Row_1 \vee Row_3 \vee Row_5 \vee Row_6
$$

Now, to be in row 1 means that $P, Q,$ and $R$ are all true. So, the sentence
$Row_1$ can be formulated by means of the following conjunction:

$$
  P\conj Q\conj R
$$

$Row_3$ is a sentence asserting that $P$ is true, $Q$ is false, and $ R$ is
true. This can be formulated as follows:

$$
  P\conj\neg Q\conj R
$$

Formulating the sentences $Row_5$ and $Row_6$ in similar fashion, we can express
the desired sentence corresponding to the above truth table by the following disjunction:

$$
  (P\conj  Q\conj R) \vee (P\conj\neg  Q\conj R) \vee (\neg P\conj  Q\conj R)
  \vee (\neg P\conj  Q\conj\neg R)
$$

With only one exception, this technique is fully generalizable, and can be used
to construct a sentence using only $\neg,\conj,$ and $\disj$ which expresses any
truth function with any number of arguments. The one case that it doesn't cover
is the degenerate case in which the truth function in question always returns
the truth value $\false$. But this truth function is expressible by the sentence
$P\conj\neg P$. So, it appears that the set of connectives $\neg,\conj,\disj$ is
all that we need complete.

In fact, we can push things a little further. Given the following equivalence:a

$$ \ph\conj \psi \equiv \neg\ph\disj\neg\psi $$

every conjunction can be replaced with a sentence that uses only $\neg$ and
$\disj$. So these two connectives alone would suffice.

Can we make do with just one connective? The answer, it turns out, is yes (see
@exr-sheffer below)!

:::{#exr-sheffer .exercise}
{{< include /content/exercises/sheffer.qmd >}}
:::

### Validity

Let us gather all of our semantic rules together. For any sentences, $\ph$ and $\psi$:

(Atomic Sentences):
If $\ph$ is an atom, then $v^\si(\ph)=\si(\ph)$.

(Negation):
$v^\si(\neg\ph)=\true$ iff
$v^\si(\ph)=\false$.

(Conjunction):
$v^\si(\ph\conj\psi)=\true$ iff
$v^\si(\ph)=\true$ and $v^\si(\psi)=\true$.

(Disjunction):
$v^\si(\ph\disj\psi)=\true$ iff
$v^\si(\ph)=\true$ or $v^\si(\psi)=\true$.

(Conditional):
$v^\si(\ph\imp\psi)=\false$ iff
$v^\si(\ph)=\true$ and $v^\si(\psi)=\false$.

(Biconditional):
$v^\si(\ph\iff\psi)=\true$ iff
$v^\si(\ph)=v^\si(\psi)$.

Taken together, these rules specify the meanings of the propositional connectives, and they
allow us to compute the truth or falsehood of any sentence in the
language L$_P$ on a given interpretation of the language. This is enough to
supply us with a precise standard for argumentative validity.

Consider, for example, the argument:

$$
\frac{\textrm{Either James is sick at home or the store is closed
\hspace{3mm},\hspace{3mm} The store is not closed}}{\textrm{James is sick at home}}
$$

Letting:

$P$: James is sick at home

$Q$: The store is closed

we can translate this argument into the language L$_P$ as follows:

$$ P\vee Q, \neg Q\proves P $$

To confirm that this argument is valid, we must make sure that there is no
interpretation under which the premises are true and the conclusion false. This
can be verified by means of a truth table:

|   $P$    |   $Q$    | $P\vee Q$ | $\neg Q$ |   $P$    |
| :------: | :------: | :-------: | :------: | :------: |
| $\true$  | $\true$  |  $\true$  | $\false$ | $\true$  |
| $\true$  | $\false$ |  $\true$  | $\true$  | $\true$  |
| $\false$ | $\true$  |  $\true$  | $\false$ | $\false$ |
| $\false$ | $\false$ | $\false$  | $\true$  | $\false$ |

As this truth table confirms, there is only one way of assigning truth values to
the atoms on which both of the premises are true and the conclusion false. So, the argument is valid.

Let's evaluate another argument:

$$
\frac{\textrm{The team improves if they either train hard or
get a new coach
\hspace{3mm},\hspace{3mm} The team improves but they did not get a
new coach}}{\textrm{The team trained hard}}
$$

Letting:

$P$: The team improves

$Q$: The team trains hard

$R$: The team gets a new coach

the argument is:

$$ (Q\vee R)\imp P, P\conj \neg R\proves Q $$

Again we can check the validity of this argument by means of a truth table:

|   $P$    |   $Q$    |   $R$    | $(Q\vee R)\imp P$ | $P\conj \neg R$ |   $Q$    |
| :------: | :------: | :------: | :---------------: | :-------------: | :------: |
| $\true$  | $\true$  | $\true$  |      $\true$      |    $\false$     | $\true$  |
| $\true$  | $\true$  | $\false$ |      $\true$      |     $\true$     | $\true$  |
| $\true$  | $\false$ | $\true$  |      $\true$      |    $\false$     | $\false$ |
| $\true$  | $\false$ | $\false$ |      $\true$      |     $\true$     | $\false$ |
| $\false$ | $\true$  | $\true$  |     $\false$      |    $\false$     | $\true$  |
| $\false$ | $\true$  | $\false$ |     $\false$      |    $\false$     | $\true$  |
| $\false$ | $\false$ | $\true$  |     $\false$      |    $\false$     | $\false$ |
| $\false$ | $\false$ | $\false$ |      $\true$      |    $\false$     | $\false$ |

The fourth row of the table provides us with a counterexample. If $P$ is true
and $Q$ and $R$ are both false, then the premises are both true and the
conclusion false. So, the argument is invalid.
