## Proofs in Propositional Logic

The truth table method is a perfectly adequate means of assessing argumentative
validity. To ascertain whether or not an argument is valid simply check all the
possible assignment of truth and falsehood to the atoms, and confirm that there
is no assignment under which all of the premises are true and the conclusion
false. While adequate, this approach very quickly becomes unwieldy---an
argument involving $n$ atoms, requires a truth table with $2^n$ rows. A much
more tractable approach would be to develop a system of reasoning by which an
argument can be shown to be valid by giving a proof of its conclusion from its
premises. In the remainder of this chapter, we will develop such a proof system
for propositional logic.

We will represent proofs in propositional logic using the same Fitch-style
notation for nested sequences that we employed in the context of syllogistic
logic. Our proof system will be based on several rules of inference. These rules
will be organized so that we have exactly two rules describing the logical
behavior of each of the five connectives---so ten rules in total. With each of
the connectives, there will be associated one rule which describes how
connectives of that sort are introduced into proofs, and another which describes
how they are removed, or eliminated, from proofs. Let's begin with the rules for negation.

### The Rules for Negation

The rule by which negations are eliminated from proofs asserts that double
negations can be cancelled. We will call this rule 'negation elimination' and
represent it by $\neg$E.

($\neg$E): From the sentence $\neg\neg\ph$, you may infer the sentence $\ph$.

The rule of 'negation introduction' is essentially the same as the rule of
reductio underwriting proofs by contradiction in syllogistic logic. In this
case, to apply the rule, we posit a hypothesis and deduce from it a pair of
contradictory sentences, that is, a sentence and its negation. Having done so,
we discharge the initial hypothesis and conclude that its negation is true. The
rule can be stated as follows:

($\neg$I): If from the hypothesis $\ph$ you can derive $\psi$ and $\neg\psi$,
you may infer the sentence $\neg\ph$.

Using these rules, we can establish the validity of the law of explosion:

$$ \ph,\neg\ph\proves\psi $$

in much the same way that we did in the setting of syllogistic logic. Here is
the proof:

:::{.lproof}

    1.  | |_  \neg\psi              [Hypothesis]
    2.  | |   \varphi               [Premise]
    3.  | |   \neg\varphi           [Premise]
    4.  | \neg\neg\psi                [$\neg$I: 2, 3]
    5.  | \psi                         [$\neg$E: 4]

:::

The proof begins by positing $\neg\psi$ as a hypothesis. Because we already have
a contradiction at our disposal in the pair of premises $\ph$ and $\neg\ph$, we
can immediately lay them down and discharge the hypothesis and infer, by the
rule of negation introduction, the sentence $\neg\neg\psi$. From this, we can
infer $\psi$ by the rule of negation elimination.

### The Rules for the Conditional

Next, we will describe the rules that determine the logical behavior of the
conditional operator. As was the case with negation, we will have two rules, one
describing the elimination of conditionals from proofs and the other describing
their introduction into proofs. The rule of 'conditional elimination' is as
follows:

($\imp$E): From $\ph$ and $\ph\imp\psi$, you may infer $\psi$.

This rule is sometimes referred to by its Latin designation _modus ponens_.[^modus-ponens] To
see how the rule can be applied in a proof, consider the following argument,
often referred to as _modus tollens_:

$$ \neg\psi, \ph\imp\psi\proves\neg\ph $$

The proof of this argument's validity is as follows:

:::{.lproof}

    1.  | |_  \varphi              [Hypothesis]
    2.  | |   \varphi\rightarrow\psi               [Premise]
    3.  | |   \psi           [$\rightarrow$E: 1, 2]
    4.  | |   \neg\psi                [Premise]
    5.  | \neg\varphi                         [$\neg$I: 3, 4]

:::

[^modus-ponens]:
    _Modus ponens_ is short for _modus ponendo ponens_, which means roughly 'the mode, which
    by putting down, puts down'.

The rule for 'conditional introduction', like the rule for negation
introduction, licenses a method of hypothetical reasoning. In particular, it
licenses the method of conditional proof, whereby we establish a conditional by
assuming its antecedent and deriving its consequent:

($\imp$I): If from the hypothesis $\ph$ you can derive $\psi$,
you may infer the sentence $\ph\imp\psi$.

To see how this rule work, let us validate the following argument by giving a proof of the conclusion from
the premises:

$$\ph\imp\psi, \psi\imp\chi\proves\ph\imp\chi$$

:::{.lproof}

    1.  | |_  \varphi              [Hypothesis]
    2.  | |   \varphi\rightarrow\psi               [Premise]
    3.  | |   \psi           [$\rightarrow$E: 1, 2]
    4.  | |   \psi\rightarrow\chi                [Premise]
    5.  | |   \chi                        [$\rightarrow$E: 3, 4]
    6.  | \varphi\rightarrow\chi                         [$\rightarrow$I: 5]

:::

This proof begins by positing the hypothesis $\ph$, which is the antecedent of
the conditional that we would like to prove. By means of the premises we derive
the sentence $\chi$ by two applications of conditional elimination. We then discharge the
initial hypothesis, and infer, by conditional introduction, the conditional
conclusion $\ph\imp\chi$.

As another example, let us show that the sentence $\ph\imp(\psi\imp\ph)$ is a
logical truth. This is equivalent to showing that the following argument is
valid:

$$ \proves\ph\imp(\psi\imp\ph) $$

Here is the proof:

:::{.lproof}

    1.  | |_  \varphi              [Hypothesis]
    2.  | | |_ \psi               [Hypothesis]
    3.  | | |   \varphi           [Reiteration: 1]
    4.  | |   \psi\rightarrow\varphi                [$\rightarrow$I: 3]
    5.  | \varphi\rightarrow(\psi\rightarrow\varphi)  [$\rightarrow$I: 4]

:::

Note that in line 3, the hypothesis posited in line 1 is reiterated in the
context of a subproof. This is generally allowed, provided the subproof appears
in the same context in which the sentence that is reiterated is first derived.

One final example:

$$\ph\imp\psi\proves\neg\psi\imp\neg\ph$$

:::{.lproof}

    1.  | |_  \neg\psi              [Hypothesis]
    2.  | | |_ \varphi               [Hypothesis]
    3.  | | |   \varphi\rightarrow\psi           [Premise]
    4.  | | | \psi                [$\rightarrow$E: 2, 3]
    5.  | | | \neg\psi            [Reiteration: 1]
    6.  | | \neg\varphi           [$\neg$I: 4, 5]
    7.  | \neg\psi\rightarrow\neg\varphi  [$\rightarrow$I: 6]

:::

### The Rules for Conjunction

Next, we turn to the rules governing the conjunction operator. Here, the
introduction and elimination rules are relatively straightforward:

($\conj$E): From $\ph\conj\psi$, you may infer either the sentence $\ph$ or the sentence $\psi$.

($\conj$I): From $\ph$ and $\psi$, you may infer the sentence $\ph\conj\psi$.

It is easy to verify, using truth tables, that the following equivalence holds:

$$ \ph\imp(\psi\imp\chi) \equiv (\ph\conj\psi)\imp\chi $$

Let's give a proof-theoretic demonstration of this equivalence by showing that the
following two arguments are valid:

$$\ph\imp(\psi\imp\chi) \proves (\ph\conj\psi)\imp\chi$$

and

$$(\ph\conj\psi)\imp\chi \proves \ph\imp(\psi\imp\chi)$$

The proof of the first is as follows:

:::{.lproof}

    1.  | |_  \varphi\wedge\psi              [Hypothesis]
    2.  | |  \varphi                          [$\wedge$E: 1]
    3.  | |  \varphi\rightarrow(\psi\rightarrow\chi)    [Premise]
    4.  | |  \psi\rightarrow\chi                        [$\rightarrow$E: 2, 3]
    5.  | |   \psi                              [$\wedge$E: 1]
    6.  | |   \chi                                [$\rightarrow$E: 4, 5]
    7.  | (\varphi\wedge\psi)\rightarrow\chi      [$\rightarrow$I: 6]

:::

Here's the proof of the second:

:::{.lproof}

    1.  | |_  \varphi              [Hypothesis]
    2.  | | |_  \psi                          [Hypothesis]
    3.  | | |   \varphi               [Reiteration: 1]
    4.  | | |   \varphi\wedge\psi     [$\wedge$I: 2, 3]
    5.  | | |   (\varphi\wedge\psi)\rightarrow\chi  [Premise]
    6.  | | |   \chi                    [$\rightarrow$E: 4, 5]
    7.  | | \psi\rightarrow\chi         [$\rightarrow$I: 6]
    8.  | \varphi\rightarrow(\psi\rightarrow\chi)   [$\rightarrow$I: 7]

:::

:::{#exr-proofs-in-p .exercise}
{{< include /content/exercises/proofs-in-p.qmd >}}
:::
