---
bibliography: "propositional-logic.bib"
number-sections: true
crossref:
  chapters: true
---

{{< include /assets/macros/macros.qmd >}}

# Propositional Logic

{{< include introduction.qmd >}}

{{< include syntax.qmd >}}

## The Meaning of the Propositional Connectives

### Truth Tables

Our next task is to explain what makes an argument in the language L$_P$ a valid
argument. Just as before, the idea of argumentative validity will be expressed
in terms of necessary truth preservation. An argument is valid just in case the
truth of the conclusion follows necessarily from that of the premises. Moreover,
the relevant notion of necessity will still be made out in semantic terms. An
argument is valid just in case there is no intepretation of the non-logical
elements of the language under which the premises are true and the conclusion is
false.

What are the non-logical elements of the language L$_P$? In this case, they are
the atoms. These, naturally, are meant to stand for the sort of simple
propositions out of which compound propositions are constructed. So, an argument
is valid just in case the truth of the conclusion follows from that of the
premises, no matter what propositions the atoms stand for.

But what exactly is a proposition? From the perspective of the general
philosophy of language, this, of course, is a complicated question. But from the
point of view of truth-functional propositional logic, it has a fairly
straightforward answer. In the context of logic, what is important about an
intepretation of the non-logical elements of a language is that such an
interpretation serves to underwrites a specific truth valuation of the sentences
of the language. Since we are dealing exclusively with truth-functional
operations, the truth values of compound sentences will be fully determined by
the truth values of the component sentences out of which they are formed. In
this way, the truth values of all the sentences of the language will supervene
on the truth values of the atomic ones.

So, while the atomic sentences do represent simple propositions, the only
feature of these propositions that is semantically relevant, in the sense that
it contributes to assessing the truth values of others sentences in the
language, is their own truth or falsehood. Thus, in this context, we may think
of a simple proposition as nothing more than the bearer of a truth value, and
the possible semantic values of the atoms as the possible truth values of the
propositions they express. The only assumptions we will make about these simple
propositions are (1) that each is _logically contingent_ in the sense that each
is a proposition that may be either true or false; and (2) that they are
_logically independent_ of each other in the sense that the truth or falsehood
of any one such proposition imposes no constraints on the truth or falsehood of
any other.

This means that, we will include among our interpretations of the
language all possible assignments of truth values to the atoms. We thus arrive
at the following definition:

:::{#def-p-interpretation .definition}
An _interpretation_ of the language L$_P$ is a function $\sigma$ which assigns
to each of the atoms a truth value, i.e., an object from the set $\{\true,
  \false\}$.
:::

To complete our specification of the semantics for the language, we must explain
how a given interpretation $\si$ determines a unique truth valuation $v^\si$ for the
language. In doing so, we will, in effect, be explaining the meanings of the
logical elements of the syntax.

For the atomic sentences, the truth value of a sentence is given directly by the
interpretation as follows:

(Atomic Sentences):
If $\ph$ is an atom, then $v^\si(\ph)=\si(\ph)$.[^atom]

[^atom]:
    Strictly speaking, the occurrence of '$\ph$' that appears as an
    argument of $v^\si$ stands for an atomic sentence, whereas the occcurence
    of '$\ph$' that appears as an argument of $\si$ stands for an atom. However,
    for ease of exposition, we will generally treat as identical an atomic
    sentence and the atom from which it is composed.

To assign truth values to compound sentences, we must introduce additional
semantic rules, specifying the meaning of the propositional connectives. We will
do so with the aim of interpreting the propositional connectives as effecting
roughly the same semantic operations as the ordinary English locutions to which
they correspond in @fig-connectives.

Let's begin with negation. We have already said that the truth-functional
operation effected by negation is that of transforming one sentence into another
sentence that is true just in case the original sentence is false. This can be
captured by the following rule:

(Negation):
For any sentence $\ph$: $v^\si(\neg\ph)=\true$ iff
$v^\si(\ph)=\false$.

Notice the 'iff' here. Since we are still assuming that every sentence is either
true or false, and that no sentence is both, it follows from our rule for
negation that if $v^\si(\ph)=\true$, then $v^\si(\ph)=\false$.

Now, let's consider conjunction. Again, as we've already said the
truth-functional operation of conjunction takes two sentences and returns a new
sentence which is true iff both of those sentences are true. We can describe
this operation as follows:

(Conjunction):
For any sentences $\ph$ and $\psi$: $v^\si((\ph\conj\psi))=\true$ iff
$v^\si(\ph)=\true$ and $v^\si(\psi)=\true$.

With the rules for negation and conjunction in place, we can now consider the
truth conditions for more complicated compound sentences, such as $\neg(P\conj
\neg Q)$. How does the truth value of this sentence depend upon the truth values
of the atoms $P$ and $Q$, appearing in it? By the rule for negation, the
sentence $\neg(P\conj\neg Q)$ is true iff the sentence $(P\conj\neg Q)$ is
false. By the rule for conjunction, $(P\conj\neg Q)$ is false iff either $P$ is
false or $\neg Q$ is false. Since $\neg Q$ is false iff $Q$ is true, the whole
sentence $\neg(P\conj\neg Q)$ is true iff either $P$ is false or $Q$ is true (or
both).

One particularly convenient format for expressing the truth conditions for
compound sentences is called a truth table. In a truth table, each row
corresponds to a different possible assignment of truth values to the atoms
appearing in a compound sentence, with each of these atoms being assigned a
separate column. The final column in the table then specifies the corresponding
truth values of the compound sentence in question. For example, a truth table
for the sentence $\neg(P\conj \neg Q)$ is as follows:

|   $P$    |   $Q$    | $\neg(P\conj \neg Q)$ |
| :------: | :------: | :-------------------: |
| $\true$  | $\true$  |        $\true$        |
| $\true$  | $\false$ |       $\false$        |
| $\false$ | $\true$  |        $\true$        |
| $\false$ | $\false$ |        $\true$        |

Note that this truth table has four rows. That is because the sentence in
question contains two atoms. Since each atom can take one of two truth values,
in order to countenance all possible interpretaions of the atoms, we need
$2\times 2 = 4$ rows. If we considered a sentence containing three distinct
atoms, we would need a truth table with $2 \times 2\times 2 = 8$ rows. In
general, a sentence with $n$ distinct atoms requires a truth table with $2^n$
rows.

When populating the initial columns in a truth table, it is important to ensure that
all possible interpretations of the atoms are countenanced. The most
straightforward way to ensure that this is the case is to adopt the following
procedure. In the first column, fill in the first half of the rows with $\true$
and the second half with $\false$. In the second column, fill in the first
quarter of the rows with $\true$, the second quarter with $\false$, the third
quarter with $\true$, and the last quarter with $\false$. Continue in this way,
writing down alternating blocks of $\true$ and $\false$, at each new column cutting
the size of the blocks in half, until you reach the last column corresponding to
an atom in which $\true$ and $\false$ alternate in every row.

### Logical Equivalence

Now, let's return to our specification of the meanings of the propositional
connectives. Disjunction corresponds to the English language operation 'either
... or ---'. Now, in natural language there exists a certain ambiguity in how we
interpret such expressions. Sometimes we interpret these expressions
'exclusively' as meaning that one of the two component sentences is true but not
both. For instance:

Either you may have coffee or you may have tea.

In other cases, we interpret disjunctions 'inclusively' as meaning that at least
one, and possibly both, of the component sentences are true, as in:

Either the train is late or the schedule posted online is wrong.

In specifying the meaning of the disjunction operator in the language L$_P$, we
will assume that it signifies inclusive disjunction, and hence that a
disjunction is rue if either
(or both) of its component sentences is true:

(Disjunction):
For any sentences $\ph$ and $\psi$: $v^\si((\ph\conj\psi))=\true$ iff
$v^\si(\ph)=\true$ or $v^\si(\psi)=\true$ (or both).

The truth table for the sentence $P\vee Q$ is as follows:

|   $P$    |   $Q$    | $P\vee Q$ |
| :------: | :------: | :-------: |
| $\true$  | $\true$  |  $\true$  |
| $\true$  | $\false$ |  $\true$  |
| $\false$ | $\true$  |  $\true$  |
| $\false$ | $\false$ | $\false$  |

- Add Exercise for exclusive disjunction
- Explain why we need parentheses by comparing the two different trees for
  $P\conj Q\vee R$
- Discuss the truth functional significance of the conditional and the paradoxes of the
  material conditional. Is a conditional true if the antecedent is false? What
  if both antecedent and consequent are true, but the truth of the antecedent is
  irrelevant to that of the consequent?
- Discuss the notion of logical equivalence and give the example of
  $P\rightarrow Q$ and $\neg(P\conj \neg Q)$.
- Add exercise to check for logical equivalence by means of truth tables.
- Add exercise to check self-duality.
- Add exercise about logical puzzle.
- Discuss the truth functional significance of the biconditional. Introduce the
  notion of logical truth and explain how logical equivalence can be expressed
  in terms of logical truth.

## References {.unnumbered}
