## Berry's Paradox

{{< include ../../assets/macros/macros.qmd >}}

- There are twenty-six letters in the English alphabet.

- Admitting one additional character to mark both the space
  between words and leading and trailing spaces, there are $27^{79}$ expressions
  with fewer than eighty characters.

  $$
  \underbrace{\overline{27} \times \overline{27} \times \overline{27} \times
  \cdots \times \overline{27}}_{79}= 27 ^ {79}
  $$

## Berry's Paradox

- The vast majority of these expressions will be nonsense expressions like:

  $$
  \textrm{asdlkjsdl goiwejrkwmfw sdsf se asfsd f}
  $$

- A few will be intelligible noun phrases, such as:

  $$
    \textrm{the tallest building in Chicago}
  $$

  $$
    \textrm{the present king of France}
  $$

## Berry's Paradox

- A much smaller selection still will be noun phrases denoting positive integers
  ($1, 2, 3\ldots$), for example:

  $$
  \textrm{\scriptsize{the sum of twelve and seventeen}}
  $$

  $$
  \textrm{\scriptsize{the first prime number greater than the number of stars in the Milky Way}}
  $$

- The class of positive integers named by any such phrase, being finite, must
  have a largest member. Call this number $N$.

## Berry's Paradox

- Then, $N+1$ is the smallest positive integer not
  describable with fewer than eighty characters.

- But, then $N+1$ _is_
  describable with fewer than eighty characters, namely, by the phrase:

  $$
  \textrm{\scriptsize{the smallest positive integer not describable with fewer than eighty
  characters}}
  $$

- So the number $N+1$ is both describable and not describable with
  fewer than eighty characters, which is a contradiction!
